version: '3.7'

services:
  proxy: 
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./img:/usr/share/nginx/img
    working_dir: /var/log/nginx

  server1: 
    image: mohsinkhalid/expressjs
    
  server2:
    image: mohsinkhalid/expressjs